name: Resume Checker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Docker Image Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Frontend Docker Image Build 
        run: |
          cd frontend
          docker build -t frontend:latest .

  docker_hub_login:
    name: Docker Hub Login
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
