name: Resume Checker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Docker Image Build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
       
       - name: frontend docker image build 
         run: |
           cd frontend
           docker build -t frontend:latest .

jobs:
  docker_hub_login:
    runs-on: ubuntu-latest
    name: Docker Hub login

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      