name: Resume Checker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Frontend Docker Image Build 
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/projectalpha:frontendlatest .
      
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/projectalpha:frontendlatest
